import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import SmartHeader from "@/components/SmartHeader";
import {
  Users,
  Lightbulb,
  Target,
  Sparkles,
  ArrowRight,
  CheckCircle2,
  Globe,
  Heart,
  TrendingUp,
  Shield,
  Zap
} from "lucide-react";

interface Service {
  title: string;
  description: string;
  icon: any;
}

interface TeamMember {
  name: string;
  role: string;
  image?: string;
}

const SERVICES: Service[] = [
  {
    title: "Asset Development",
    description: "We bridge individuals and communities to generate and transfer value by developing platforms that enable economic empowerment and sustainable growth.",
    icon: Target,
  },
  {
    title: "Personnel Development",
    description: "We empower individuals and staff to understand, adopt and enhance technologies for sustainable service delivery and professional excellence.",
    icon: Users,
  },
  {
    title: "Innovation, Analytics & Diffusion",
    description: "We research innovations, carry out analytics and design sustainable diffusion mechanisms to empower builders and drive technological adoption.",
    icon: Lightbulb,
  },
];

const CORE_VALUES = [
  { icon: Heart, title: "Social Impact", description: "Measurable outcomes aligned with UN SDGs" },
  { icon: Shield, title: "Transparency", description: "Multi-sig governance and open operations" },
  { icon: Globe, title: "Decentralization", description: "Community-driven decision making" },
  { icon: TrendingUp, title: "Sustainability", description: "Long-term value creation" },
];

const CORE_CAPABILITIES = [
  "Needs Assessment",
  "Reverse Engineering",
  "Systems Design",
  "Asset Development",
  "Personnel Development",
  "Innovation Diffusion & Campaigns",
  "Analytics & Extension",
];

const TEAM_MEMBERS: TeamMember[] = [
  { name: "Zyre", role: "The Extensionist", image: "/team/zyre.jpeg" },
  { name: "Ewuru Samson Uzoma", role: "Software Solutions Expert", image: "/team/samson.jpeg" },
  { name: "Nwachukwu Victor", role: "CEO at Legendaire", image: "/team/nwachukwu.jpg" },
  { name: "Jamike Gabeson", role: "Blocksquare Ambassador", image: "/team/gabe.jpeg" },
  { name: "Nduka Patience M.A.Ed", role: "Translations Manager", image: "/team/nduka.jpg" },
  { name: "Nsikak Nkan", role: "Blocksquare Ambassador", image: "/team/nsikak.jpg" },
  { name: "Favor Ukah", role: "CEO at New Eden Comfort Realty", image: "/team/ukah.png" },
  { name: "Ndip Youville", role: "International Correspondent", image: "/team/ndip.jpg" },
  { name: "Subenghu Excel", role: "Analyst Coach", image: "/team/subenghu.jpg" },
];

const FAQ = [
  {
    question: "Where is Libertas Alpha based?",
    answer: "Libertas Alpha is strategically positioned in Nigeria, recognized as the epicenter of digital transformation and the real-world asset revolution in Africa.",
  },
  {
    question: "What is the purpose of Libertas Alpha?",
    answer: "Our mission is to foster an ecosystem that nurtures asset development, personnel growth, and cutting-edge innovation, all while harnessing the power of data analytics for sustainable social impact.",
  },
  {
    question: "How does Libertas Alpha measure social impact?",
    answer: "We measure social impact through objective SDG metrics and contribution metrics, quantified through Impact Tokens that represent the direct, measurable value created by our contributors.",
  },
  {
    question: "What makes Libertas Alpha Technologies different from other companies?",
    answer: "We operate on a non-profit ideology powered by Human Nodes, utilize Impact Equity systems, and employ decentralized governance with transparent, multi-signature treasury controls.",
  },
  {
    question: "How does Libertas ensure financial sustainability?",
    answer: "Revenue generated by our ventures is strictly governed by Multi-Signature Community Treasury Smart Contracts, ensuring transparent flow and reinvestment into ecosystem and social impact projects.",
  },
  {
    question: "What type of organizations does Libertas Alpha Partner with?",
    answer: "We partner with NGOs, academic institutions, compliant financial service providers, and organizations that align with the UN Sustainable Development Goals.",
  },
];

/**
 * About Us Page - Company information and team
 * Premium design matching Home page aesthetics
 */
export default function About() {
  return (
    <>
      <div className="min-h-screen bg-gradient-to-br from-[#0A0628] via-[#1a0f3d] to-[#0A0628] text-white">
        {/* Animated background elements */}
        <div className="fixed inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-20 left-10 w-96 h-96 bg-purple-600/10 rounded-full blur-3xl animate-pulse"></div>
          <div className="absolute bottom-20 right-10 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl animate-pulse delay-1000"></div>
        </div>

        {/* Header */}
        <SmartHeader />

        {/* Main Content */}
        <main className="relative flex-1 px-4 py-16">
          <div className="container mx-auto max-w-6xl">
            {/* Hero Section */}
            <section className="mb-20 text-center">
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 backdrop-blur-sm mb-6">
                <Sparkles className="w-4 h-4 text-purple-400" />
                <span className="text-sm font-medium text-white/90">Empowering Growth, Innovation & Excellence</span>
              </div>

              <h1 className="text-5xl md:text-6xl font-bold mb-6">
                <span className="bg-gradient-to-r from-purple-400 via-pink-400 to-blue-400 bg-clip-text text-transparent">
                  About Libertas Alpha
                </span>
              </h1>

              <p className="text-xl text-white/70 max-w-4xl mx-auto leading-relaxed mb-8">
                We're driven by a passion for empowering growth, innovation, and excellence. Our mission is to foster an ecosystem that nurtures asset development, personnel growth, and cutting-edge innovation, all while harnessing the power of data analytics to create measurable social impact.
              </p>
            </section>

            {/* Mission Statement */}
            <section className="mb-20">
              <div className="p-10 rounded-3xl bg-gradient-to-r from-purple-600/20 to-blue-600/20 border border-purple-500/30 backdrop-blur-sm">
                <div className="flex items-center gap-3 mb-6">
                  <Zap className="w-8 h-8 text-purple-400" />
                  <h2 className="text-3xl font-bold text-white">Our Mission</h2>
                </div>
                <p className="text-white/80 text-lg leading-relaxed">
                  We are dedicated to realizing freedom through innovation aligned with humanity's fundamental goals. We believe that true freedom in the 21st century is a tangible outcome harnessed directly from the forefront of innovation. Through decentralized systems, transparent governance, and a commitment to social impact, we're architecting a new social and economic contract that benefits all.
                </p>
              </div>
            </section>

            {/* Core Values */}
            <section className="mb-20">
              <h2 className="text-4xl font-bold text-center mb-12">
                <span className="bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
                  Our Core Values
                </span>
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                {CORE_VALUES.map((value, idx) => (
                  <div key={idx} className="group p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-sm hover:bg-white/10 transition-all hover:scale-105">
                    <value.icon className="w-10 h-10 text-purple-400 mb-4 group-hover:scale-110 transition-transform" />
                    <h3 className="text-lg font-bold text-white mb-2">{value.title}</h3>
                    <p className="text-white/60 text-sm">{value.description}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* Services Section */}
            <section className="mb-20">
              <h2 className="text-4xl font-bold text-center mb-12">
                <span className="bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
                  Our Services
                </span>
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {SERVICES.map((service, idx) => (
                  <div
                    key={idx}
                    className="group relative p-8 rounded-2xl bg-gradient-to-br from-white/5 to-white/10 border border-white/10 backdrop-blur-sm hover:border-purple-500/50 transition-all hover:scale-105"
                  >
                    <div className="absolute inset-0 bg-gradient-to-br from-purple-600/0 to-blue-600/0 group-hover:from-purple-600/10 group-hover:to-blue-600/10 rounded-2xl transition-all"></div>

                    <div className="relative">
                      <div className="p-3 bg-purple-500/20 rounded-xl text-purple-400 w-fit mb-4 group-hover:scale-110 transition-transform">
                        <service.icon className="w-8 h-8" />
                      </div>
                      <h3 className="text-xl font-bold text-white mb-3">{service.title}</h3>
                      <p className="text-white/70 leading-relaxed">{service.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* Core Capabilities */}
            <section className="mb-20">
              <div className="p-10 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-sm">
                <h2 className="text-3xl font-bold text-white mb-8 text-center">Our Core Capabilities</h2>
                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
                  {CORE_CAPABILITIES.map((capability, idx) => (
                    <div
                      key={idx}
                      className="p-4 bg-gradient-to-br from-purple-600/10 to-blue-600/10 rounded-xl border border-white/10 text-center hover:scale-105 transition-transform"
                    >
                      <CheckCircle2 className="w-5 h-5 text-purple-400 mx-auto mb-2" />
                      <p className="font-medium text-white text-sm">{capability}</p>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* Team Section */}
            <section className="mb-20">
              <h2 className="text-4xl font-bold text-center mb-12">
                <span className="bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
                  Our Leadership Team
                </span>
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {TEAM_MEMBERS.map((member, idx) => (
                  <div
                    key={idx}
                    className="group p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-sm hover:bg-white/10 transition-all hover:scale-105 text-center"
                  >
                    <div className="w-24 h-24 mx-auto mb-4 rounded-full bg-gradient-to-r from-purple-600 to-blue-600 flex items-center justify-center text-2xl font-bold overflow-hidden border-2 border-purple-500/30 group-hover:border-purple-500/50 transition-all shadow-lg shadow-purple-500/20">
                      {member.image ? (
                        <img 
                          src={member.image} 
                          alt={member.name}
                          className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
                        />
                      ) : (
                        <span className="text-white">{member.name.charAt(0)}</span>
                      )}
                    </div>
                    <h3 className="text-lg font-bold text-white mb-2">{member.name}</h3>
                    <p className="text-sm text-purple-400">{member.role}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* FAQ Section */}
            <section className="mb-20">
              <h2 className="text-4xl font-bold text-center mb-12">
                <span className="bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
                  Frequently Asked Questions
                </span>
              </h2>
              <div className="space-y-4">
                {FAQ.map((item, idx) => (
                  <details
                    key={idx}
                    className="group p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-sm hover:bg-white/10 transition-all cursor-pointer"
                  >
                    <summary className="font-bold text-white flex items-center justify-between list-none">
                      <span className="flex-1">{item.question}</span>
                      <ArrowRight className="w-5 h-5 text-purple-400 group-open:rotate-90 transition-transform" />
                    </summary>
                    <p className="text-white/70 mt-4 leading-relaxed">{item.answer}</p>
                  </details>
                ))}
              </div>
            </section>

            {/* Medium CTA */}
            <section className="mb-20">
              <div className="text-center p-12 rounded-3xl bg-gradient-to-r from-purple-600/20 to-blue-600/20 border border-purple-500/30 backdrop-blur-sm">
                <h2 className="text-3xl font-bold text-white mb-4">Read Our Latest Insights</h2>
                <p className="text-white/70 mb-6 max-w-3xl mx-auto leading-relaxed">
                  Dive deeper into Libertas Alpha vision, strategies, and impact stories. Our Medium publication features in-depth articles on blockchain innovation, asset development, personnel growth, and the future of decentralized ecosystems.
                </p>
                <a href="https://medium.com/@libertasalpha_10290" target="_blank" rel="noopener noreferrer">
                  <Button size="lg" className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white border-0 shadow-xl shadow-purple-500/50 px-8">
                    Explore Our Medium Publication
                    <ArrowRight className="ml-2 w-5 h-5" />
                  </Button>
                </a>
              </div>
            </section>

            {/* Final CTA */}
            <section>
              <div className="text-center p-12 rounded-3xl bg-gradient-to-r from-purple-600/20 to-blue-600/20 border border-purple-500/30 backdrop-blur-sm">
                <h3 className="text-3xl md:text-4xl font-bold text-white mb-4">Join Our Movement</h3>
                <p className="text-white/70 mb-8 text-lg max-w-2xl mx-auto">
                  Whether you're a Human Node looking to contribute your skills, a strategic partner seeking collaboration, or a liquidity provider wanting to fuel our mission, we invite you to be part of something transformative.
                </p>
                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                  <Link href="/dashboard">
                    <Button size="lg" className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white border-0 shadow-xl shadow-purple-500/50 px-8">
                      Get Started
                    </Button>
                  </Link>
                  <Link href="/support">
                    <Button size="lg" variant="outline" className="border-white/20 text-white hover:bg-white/10 backdrop-blur-sm px-8">
                      Contact Us
                    </Button>
                  </Link>
                </div>
              </div>
            </section>
          </div>
        </main>

        {/* Footer */}
        <footer className="relative border-t border-white/10 backdrop-blur-sm bg-black/20 py-12 mt-20">
          <div className="container mx-auto px-4">
            <div className="flex flex-col md:flex-row justify-between items-center gap-6">
              <div className="flex items-center gap-3">
                <img src="/libertas-logo-white.png" alt="Libertas Alpha" className="h-8 w-auto" />
                <span className="text-sm text-white/60">© 2026 Libertas Alpha Technologies</span>
              </div>
              <div className="flex gap-6">
                <Link href="/whitepaper" className="text-white/60 hover:text-white transition-colors text-sm">
                  Whitepaper
                </Link>
                <Link href="/projects" className="text-white/60 hover:text-white transition-colors text-sm">
                  Projects
                </Link>
                <Link href="/about" className="text-white/60 hover:text-white transition-colors text-sm">
                  About
                </Link>
                <Link href="/support" className="text-white/60 hover:text-white transition-colors text-sm">
                  Support
                </Link>
              </div>
            </div>
          </div>

        </footer>
      </div>
    </>
  );
}
