import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import { ArrowLeft, Download, ChevronRight, FileText, Share2, Printer, Star, Layout, Users, ShieldCheck, Zap, Globe, Cpu, LineChart } from "lucide-react";
import { useState, useEffect } from "react";
import { motion, AnimatePresence, useScroll, useSpring } from "framer-motion";
import { toast } from "sonner";
import SmartHeader from "@/components/SmartHeader";

interface Section {
  id: string;
  title: string;
  icon: React.ReactNode;
  content: string;
}

const WHITEPAPER_SECTIONS: Section[] = [
  {
    id: "executive-summary",
    title: "1. Executive Summary",
    icon: <Star className="w-5 h-5" />,
    content: `Libertas Alpha is dedicated to realizing freedom through innovation aligned with humanity's fundamental goals. These can be encapsulated by the United Nations Sustainable Development Goals (SDGs). This whitepaper presents a revolutionary framework for decentralized innovation that addresses the inherent limitations of traditional, profit-driven network models by adopting a non-profit ideology powered by a network of dedicated Human Nodes.

Our model does not rely on speculative economics but instead utilizes an Impact Equity system, providing contributors verifiable ownership of the social, environmental, and financial outcomes created by their contributions, quantified through transferable Impact Tokens.

Revenue generated by Ventures is strictly governed by a Multi-Signature Community Treasury Contract to ensure transparent flow into the ecosystem and social impact projects.

With a strategic focus on Nigeria, recognized as a global epicenter for the Real-World Asset (RWA) revolution, Libertas Alpha employs a Layer-Agnostic technological approach and integrates the scientific strengths of the Triple Helix model. Our unwavering commitment to transparency, decentralized capital flow, and measurable social impact forms the bedrock of our mission to create a more equitable, prosperous, and truly free future for all.`,
  },
  {
    id: "introduction",
    title: "2. The Quest for Freedom",
    icon: <Users className="w-5 h-5" />,
    content: `Humanity seeks freedom at different levels. Technology is proof that humanity has evolved over time. With the interconnectedness of humanity on the internet, the pursuit of freedom remains the ultimate human aspiration.

Libertas Alpha posits that in the 21st century, true freedom is a tangible outcome harnessed directly from the forefront of innovation. This philosophy underpins Libertas Alpha's unique approach: leveraging cutting-edge technologies, not as ends in themselves, but as powerful instruments for profound societal impact. We operate on the conviction that a non-profit model creates the most impact; driven by selfless contributors–our "Human Nodes". This conviction offers a superior and more ethical alternative to the governance challenges prevalent in profit driven Networks. Being guided by the United Nations Sustainable Development Goals (SDGs), our innovations translate to tangible social impact.

This whitepaper elucidates the foundational philosophy, operational structure, technological foundation and strategic SDG initiatives of Libertas Alpha, demonstrating how our decentralized model is poised to redefine the landscape of digital transformation through real-world asset integration.`,
  },
  {
    id: "philosophy",
    title: "3. Foundational Philosophy",
    icon: <Cpu className="w-5 h-5" />,
    content: `Freedom as an active state of liberation is achievable through relentless and purposeful innovation. This perspective extends to the emancipation from systemic inefficiencies, lack of access, and centralized controls. By pioneering new technologies within the decentralized Web3 space, Libertas Alpha dismantles these barriers, creating new pathways for empowerment and self-sufficiency.

3.1. Human Nodes
We identify a critical vulnerability in many contemporary network architectures: their susceptibility to profit-driven motives. Our revolutionary solution is the concept of Human Nodes operating under a non-profit ideology and incentivized by Impact Equity. For skill based executions, we deploy Soulbound Credentials (SBTs) to ensure that expertise remains non-speculative and bound to identity.

3.2. Universal Goals (SDGs)
A cornerstone of our vision is the unwavering belief that humanity shares fundamental universal goals, eloquently captured by the UN SDGs. Libertas Alpha meticulously aligns its initiatives with these 17 global objectives, ensuring every project contributes directly to addressing critical global challenges.

3.3. Impact Equity
Human Nodes gain verifiable ownership of the impact created by their contributions. This "equity" is measured by objective SDG metrics and contribution metrics, quantified through Impact Tokens which represent the direct, measurable value created.`,
  },
  {
    id: "nigerian-imperative",
    title: "4. The Nigerian Imperative",
    icon: <Globe className="w-5 h-5" />,
    content: `Libertas Alpha strategically positions its operations within Nigeria, recognizing the nation as the undeniable epicenter of a global digital transformation and real-world asset (RWA) revolution.

The confluence of a vast youthful population, a dynamic economic landscape, and a leading position in digital asset usage makes it an ideal crucible for decentralized innovation. Nigeria is the primary host to establish Libertas Alpha related ventures. This strategic focus is about harnessing Nigerian ingenuity to create scalable models for sustainable development that can be replicated globally. The existing legal framework (e.g., the Land Use Act of 1978) provides a stable environment within which digital asset integration and tokenization can occur, making Nigeria a fertile ground for high-impact, value-centric projects.`,
  },
  {
    id: "operational-structure",
    title: "5. Operational Structure",
    icon: <Layout className="w-5 h-5" />,
    content: `The Libertas Alpha Network is a comprehensive, decentralized ecosystem structured around various interconnected components—Outfits, Departments, and Ventures—all operating under a non-profit ideology and leveraging smart contracts and DApps. This structure embodies an adapted Triple Helix model.

5.1. Outfits: community-driven development translating ideas into sustainable systems.
5.2. Departments: the operational backbone ensuring growth, and compliance.
5.3. Ventures: independent ideas generated within the network.
- Venture Independence: Each Venture operates as an impact-driven entity.
- Revenue Control: All revenue is routed through Multi-Signature Community Treasury.
- Governance Mandate: Adherence to the non-profit mandate is hard-coded.
- Value Flow: Contributor rewards are issued as verifiable Impact Tokens.`,
  },
  {
    id: "technology",
    title: "6. Technological Foundation",
    icon: <Zap className="w-5 h-5" />,
    content: `Libertas Alpha's operational framework is deeply rooted in blockchain technology, leveraging the best tools available rather than committing to a single chain.

6.1. Layer-Agnostic & Interoperable Deployment
Libertas Alpha adopts a Layer-Agnostic strategy. Core governance and identity layers are designed to be interoperable, but specific Ventures utilize the optimal blockchain layer (e.g., low-cost L2s for high-volume transactions, established L1s for RWA stability).

6.2. RWA Tokenization: Compliance Bridge
Tokenization of Real-World Assets (RWAs), particularly in Nigerian real estate and agriculture, using ERC-721 for unique identification and ERC-20/4626 for fractionalized equity and yield vaults.

6.3. Smart Contracts for Automated Trust
Smart contracts automate critical processes, including Impact Token issuance, Multi-Signature Treasury governance, and transparent fund allocation, managed via Reactive Smart Contracts (RSCs).`,
  },
  {
    id: "sdg-alignment",
    title: "7. SDG Alignment",
    icon: <ShieldCheck className="w-5 h-5" />,
    content: `Libertas Alpha's operational structure is designed for measurable social impact, directly contributing to key SDGs:

- SDG 1: No Poverty - Creating verifiable Impact Equity and micro-entrepreneurship.
- SDG 2: Zero Hunger - Agro Prime Movers enhances food security.
- SDG 4: Quality Education - AGD provides specialized training certified by SBTs.
- SDG 9: Innovation & Infrastructure - Building resilient DApps.
- SDG 17: Partnerships for the Goals - Encouraging global collaboration among Human Nodes.`,
  },
  {
    id: "roadmap",
    title: "8. Strategic Roadmap",
    icon: <LineChart className="w-5 h-5" />,
    content: `The initial 18-month roadmap focuses on infrastructure and knowledge base establishment.

Phase I: Q4 2025 – Q1 2026
- Launch of Contributor DApp v1.0
- Affiliate Program Standardization
- Publicity of Governance Forum
- AGD Curriculum Completion & SBT Framework

Phase II: Q2 – Q4 2026
- RWA Marketplace Launch
- Master Ventures Roll out
- International Partnership Establishment`,
  },
  {
    id: "risk-compliance",
    title: "9. Risk & Compliance",
    icon: <ShieldCheck className="w-5 h-5" />,
    content: `We view regulatory development as a primary risk vector addressed through continuous internal compliance.

- Regulatory Ambiguity: Addressed via jurisdictional-specific approach with certified legal partners.
- Off-Chain Falsification: Mitigated through strict KYA and KYC protocols and on-chain Oracles.
- Smart Contract Vulnerability: Addressed by multiple third-party security audits prior to deployment.`,
  },
  {
    id: "call-to-action",
    title: "10. Join the Movement",
    icon: <ArrowLeft className="w-5 h-5 rotate-180" />,
    content: `Libertas Alpha is architecting a new social and economic contract. We invite crucial categories of partners:

10.1. The Human Node: Contribute your impact and earn verifiable Impact Equity.
10.2. The Strategic Partner: Scale our reach through NGO, academic, or financial collaboration.
10.3. The Liquidity Provider: Fuel the mission with capital that values social return.

Together, we will ensure that technology serves humanity, making freedom a tangible reality for all.`,
  },
];

export default function Whitepaper() {
  const [activeSection, setActiveSection] = useState("executive-summary");
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001
  });

  useEffect(() => {
    const observers = new Map();
    const handleIntersect = (entries: IntersectionObserverEntry[]) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          setActiveSection(entry.target.id);
        }
      });
    };

    const observer = new IntersectionObserver(handleIntersect, {
      rootMargin: "-20% 0px -70% 0px",
      threshold: 0
    });

    WHITEPAPER_SECTIONS.forEach((section) => {
      const element = document.getElementById(section.id);
      if (element) {
        observer.observe(element);
        observers.set(section.id, element);
      }
    });

    return () => observer.disconnect();
  }, []);


  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = '/whitepaper.pdf';
    link.download = 'Libertas-Alpha-Whitepaper.pdf';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    toast.success("Download started!", {
      description: "The official Libertas Alpha whitepaper is being downloaded.",
    });
  };

  return (
    <div className="min-h-screen bg-[#0A0628] text-white selection:bg-purple-500/30">
      {/* Scroll Progress Bar */}
      <motion.div
        className="fixed top-0 left-0 right-0 h-1 bg-gradient-to-r from-purple-500 via-pink-500 to-blue-500 z-[60] origin-[0%]"
        style={{ scaleX }}
      />

      {/* Background Elements */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-purple-600/10 rounded-full blur-[120px] animate-pulse" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-blue-600/10 rounded-full blur-[120px] animate-pulse delay-1000" />
      </div>

      {/* Header */}
      <SmartHeader showAuthButtons={false} showDefaultNav={false}>
        <div className="hidden md:flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 mr-4">
          <div className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
          <span className="text-[10px] uppercase tracking-wider font-semibold text-white/60">V1.0 Official Publication</span>
        </div>
        <Button
          className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white border-0 shadow-lg shadow-purple-500/20"
          onClick={handleDownload}
        >
          <Download className="w-4 h-4 mr-2" />
          Download PDF
        </Button>
      </SmartHeader>

      <div className="container px-4 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr] gap-12 py-12">
          {/* Side Navigation */}
          <aside className="hidden lg:block">
            <div className="sticky top-32 space-y-8">
              <div>
                <h3 className="text-xs uppercase tracking-[0.2em] font-bold text-white/40 mb-6">Table of Contents</h3>
                <nav className="space-y-1">
                  {WHITEPAPER_SECTIONS.map((section) => (
                    <button
                      key={section.id}
                      onClick={() => scrollToSection(section.id)}
                      className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm font-medium transition-all group ${activeSection === section.id
                        ? "bg-white/10 text-white translate-x-1"
                        : "text-white/50 hover:text-white/80 hover:bg-white/5"
                        }`}
                    >
                      <span className={`w-1 h-4 rounded-full transition-all ${activeSection === section.id ? "bg-purple-500" : "bg-transparent group-hover:bg-white/20"
                        }`} />
                      {section.title.split(":")[0]}
                    </button>
                  ))}
                </nav>
              </div>

              <div className="p-6 rounded-2xl bg-gradient-to-br from-white/5 to-white/[0.02] border border-white/10">
                <h4 className="text-sm font-bold mb-2">Need Help?</h4>
                <p className="text-xs text-white/50 mb-4 leading-relaxed">Have questions about our mission or technical framework?</p>
                <Link href="/support">
                  <Button variant="outline" size="sm" className="w-full text-xs border-white/10 hover:bg-white/5">
                    Contact Support
                  </Button>
                </Link>
              </div>
            </div>
          </aside>

          {/* Main Content */}
          <main className="max-w-3xl mx-auto lg:mx-0 print:max-w-none print:px-0">
            {/* Title Section */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="mb-20 text-center lg:text-left"
            >
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-xs font-bold mb-6">
                <FileText className="w-3.5 h-3.5" />
                TECHNICAL WHITEPAPER
              </div>
              <h1 className="text-4xl md:text-6xl font-bold mb-8 leading-[1.1]">
                <span className="bg-gradient-to-r from-white via-white to-white/50 bg-clip-text text-transparent italic mr-2">Libertas Alpha:</span>
                <span className="bg-gradient-to-r from-purple-400 via-pink-400 to-blue-400 bg-clip-text text-transparent">Decentralized Innovation</span>
              </h1>
              <div className="flex flex-wrap items-center justify-center lg:justify-start gap-x-8 gap-y-4 text-sm text-white/50">
                <div className="flex items-center gap-2">
                  <span className="w-1 h-1 rounded-full bg-purple-500" />
                  <span className="font-medium text-white/70">Chinedu Jamike - Zyre</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="w-1 h-1 rounded-full bg-pink-500" />
                  <span>October 12, 2025</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="w-1 h-1 rounded-full bg-blue-500" />
                  <span>v1.0.0</span>
                </div>
              </div>
            </motion.div>

            {/* Sections */}
            <div className="space-y-32">
              {WHITEPAPER_SECTIONS.map((section, index) => (
                <motion.section
                  key={section.id}
                  id={section.id}
                  initial={{ opacity: 0, y: 40 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-100px" }}
                  transition={{ duration: 0.6, delay: 0.1 }}
                  className="scroll-mt-32 relative print:mb-12 print:scroll-mt-0"
                >
                  <div className="flex items-center gap-4 mb-8">
                    <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-purple-500/20 to-blue-500/20 flex items-center justify-center border border-white/10">
                      <div className="text-purple-400">{section.icon}</div>
                    </div>
                    <h2 className="text-2xl md:text-3xl font-bold text-white tracking-tight">{section.title}</h2>
                  </div>

                  <div className="prose prose-invert prose-purple max-w-none">
                    <div className="space-y-6 text-lg text-white/70 leading-relaxed font-light">
                      {section.content.split("\n\n").map((para, i) => (
                        <p key={i}>{para}</p>
                      ))}
                    </div>
                  </div>

                  {/* Decorative background number */}
                  <div className="absolute -left-16 top-0 text-[10rem] font-black text-white/[0.02] select-none pointer-events-none hidden xl:block">
                    {index + 1}
                  </div>
                </motion.section>
              ))}
            </div>

            {/* References Section */}
            <section className="mt-40 pt-20 border-t border-white/10">
              <div className="flex items-center gap-4 mb-12">
                <div className="w-12 h-12 rounded-2xl bg-white/5 flex items-center justify-center border border-white/10">
                  <Printer className="w-5 h-5 text-white/40" />
                </div>
                <h2 className="text-3xl font-bold text-white">11. References</h2>
              </div>
              <div className="grid gap-4">
                {[
                  "Libertas Alpha. (2025, August 5). NIGERIA: The Epicenter of Digital Transformation and Real-World Asset Revolution. Medium.",
                  "Libertas Alpha. (2025, June 25). Organizational structure of Libertas Alpha and why it fits as an NGO. Medium.",
                  "Libertas Alpha. (2025, June 11). Libertas Alpha: Where Technology Meets Transformative Freedom. Medium.",
                  "Libertas Alpha. (n.d.). X Profile.",
                  "Nakamoto, S. (2008). Bitcoin: A Peer-to-Peer Electronic Cash System.",
                  "Etzkowitz, H., & Leydesdorff, L. (1995). The Triple Helix, University-Industry-Government Relations. EASST Review, 14(1), 14–19.",
                  "Business Day NG. (2025, March 13). How RWA Tokenization Is Transforming Global Finance.",
                  "QuickNode Guides. (2025, Sept 22). How to Create A Soulbound Token."
                ].map((ref, i) => (
                  <div key={i} className="group flex gap-4 p-4 rounded-xl hover:bg-white/5 transition-colors border border-transparent hover:border-white/10">
                    <span className="text-purple-500 font-mono text-sm mt-1">[{i + 1}]</span>
                    <p className="text-sm text-white/50 group-hover:text-white/80 transition-colors leading-relaxed">{ref}</p>
                  </div>
                ))}
              </div>
            </section>
          </main>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-white/10 bg-black/20 py-16 mt-32 relative overflow-hidden print:mt-12">
        <div className="container px-4 text-center">
          <Link href="/" className="inline-block mb-12 group">
            <img src="/libertas-logo-white.png" alt="Libertas Alpha" className="h-12 w-auto mx-auto grayscale opacity-50 transition-all group-hover:grayscale-0 group-hover:opacity-100" />
          </Link>
          <p className="text-white/40 text-sm mb-4">Libertas Alpha Technical Whitepaper • Version 1.0.0 • Publication Date: Oct 12, 2025</p>
          <p className="text-white/20 text-xs tracking-widest uppercase">&copy; 2025 Libertas Alpha Technologies. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}

